spring:
  datasource:
    url: jdbc:mysql://192.168.1.241:3306/Blog
    username: root
    password: root
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.daresasuke.dao: debug

