spring:
  datasource:
    url: jdbc:mysql://10.4.65.211:3366/Blog
    username: root
    password: root
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.daresasuke.dao: debug
server:
  port: 80
